### ISSUE TITLE
Wrong user names in job loop

### ISSUE THREAD

**Issue by lukashermann** [kcl-nmssys/slurm-influxdb#4]
Hi,
first of all thank you for this very helpful work!
I think there is a mistake in the job loop. In line 195 and 196 you set the user variable,
```
if job['user_id'] not in user_ids:
    user = pwd.getpwuid(job['user_id'])[0]
```
but only in the case that there is a new user_id.
This leads to wrong user names (in some cases). I think you should set the username again
`user = user_ids[job['user_id']]` after the if clause.
I verified my concerns with squeue and indeed saw that your logs are assigning statistics to the wrong users in some cases.
You can also try to verify it with adding this line:
```
if user != user_ids[job['user_id']]:
    print("wrong username")
```

**Comment by xandm** [comment]
Hi,

Can you see if this fixes it? https://github.com/kcl-nmssys/slurm-influxdb/commit/e78270ecd44ec2045389c953f535c454c29ac607

Thanks,
Xand

**Comment by lukashermann** [comment]
Yes that fixes it, thanks!
